Models/Cart.cs
using System.Collections.Generic;
using System.Linq;

namespace ShoppingCart.Models
{
    public class Cart
    {
        public List<CartLine> Lines { get; set; } = new List<CartLine>();
        public virtual void AddItem(Product product, int quantity)
        {
            CartLine line = Lines.Where(p => p.Product.ProductId == product.ProductId).FirstOrDefault();
            if (line == null)
            {
                Lines.Add(new CartLine
                {
                    Product = product,
                    Quantity = quantity
                });
            }
            else
            {
                line.Quantity += quantity;
            }
        }
        public decimal ComputeTotalValues()
        {
            return Lines.Sum(p => p.Quantity * p.Product.Price);
        }
        
        public virtual void RemoveLine(Product product)
        {
            Lines.RemoveAll(p => p.Product.ProductId == product.ProductId);
        }

        public virtual void Clear()
        {
            Lines.Clear();
        }
    }
    public sealed class CartLine
    {
        public int CartLineID { get; set; }
        public Product Product { get; set; }
        public int Quantity { get; set; }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using ShoppingCart.Models;

namespace ShoppingCart.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository OrderRepository;
        private Cart cart;

        public OrderController(IOrderRepository orderRepository, Cart cartService)
        {
            OrderRepository = orderRepository;
            cart = cartService;
        }

        public IActionResult Checkout()
        {
            return View(new Order());
        }
        
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (cart.Lines.Count == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            foreach (CartLine line in cart.Lines)
            {
                if (line.Product.StockQuantity < line.Quantity)
                {
                    return RedirectToPage("/OrderFailed", new { cart = cart });
                }
            }
            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                OrderRepository.SaveOrder(order);
                cart.Clear();
                return RedirectToPage("/Completed", new { orderId = order.OrderID });
            }
            else
            {
                return View();
            }
        }
    }
}

Pages/Cart.cshtml.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShoppingCart.Models;

namespace ShoppingCart.Pages
{
    public class CartModel : PageModel
    {
        private IProductRepository productRepository;
        public CartModel(IProductRepository repository, Cart cartService)
        {
            productRepository = repository;
            Cart = cartService;
        }
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }
        public IActionResult OnPost(long productId, string returnUrl)
        {
            Product product = productRepository.Products.FirstOrDefault(p => p.ProductId == productId);
            Cart.AddItem(product, 1);
            return RedirectToPage(new { returnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(long productId, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(p => p.Product.ProductId == productId).Product);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

Pages/OrderFailed.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShoppingCart.Models;

namespace ShoppingCart.Pages
{
    public class OrderFailedModel : PageModel
    {
        public Cart cart;
        public OrderFailedModel(Cart _cart)
        {
            cart = _cart;
        }
    }
}

Pages/About.cshtml
@page "/about"
<header class="page-title pt-large pt-dark pt-plax-lg-dark" data-stellar-background-ratio="0.4">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <h1>About Us</h1>
        <span class="subheading">Few Words about us</span>
      </div>
    </div>
  </div>
</header>
<section id="about" class="container">
  <div class="row section">
    <header class="sec-heading">
      <h2>About Studio</h2>
      <span class="subheading">Lorem ipsum dolor sit amet, consectetur</span>
    </header>
    <div class="col-md-offset-1 col-md-5">
      <blockquote>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
        et dolore magna aliqua. Ut enim ad minim
        <footer><cite>by Henry Hill</cite></footer>
      </blockquote>
    </div>
    <div class="col-md-5">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi aperiam, quia expedita accusamus assumenda.
        Autem cumque, temporibus, at, suscipit totam dolore incidunt fugit amet nulla libero dignissimos labore ab
        rerum. Similique quasi eligendi quas excepturi perspiciatis. Distinctio nam sunt exercitationem.</p>
    </div>
  </div><!-- / .row -->
  <div class="row ws-m">
    <div class="col-md-12 text-center">
      <a href="#" class="btn-ghost btn-round">Get in touch</a>
    </div>
  </div>
</section>

Pages/Cart.cshtml
@page "/Cart"
@model CartModel
<header class="page-title pt-large pt-dark pt-plax-lg-dark" data-stellar-background-ratio="0.4">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h1>Cart</h1>
                <span class="subheading">Your shopping cart</span>
            </div>
        </div>
    </div>
</header>  
<div class="container section">
    <div class="row">
        <div class="col-lg-9">
            <div class="table-responsive">
                <table class="table checkout-table">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Preview</th>
                            <th>Product</th>
                            <th>Q-ty</th>
                            <th>Price</th>
                            <th>Total</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (CartLine line in Model.Cart.Lines)
                        {
                            <tr>
                                <td>@line.CartLineID</td>
                                <td><img src="lib/assets/images/shop/p-thumb-1.jpg" alt="Thumb product image"></td>
                                <td>@line.Product.Name</td>
                                <td>@line.Quantity</td>
                                <td>@line.Product.Price.ToString("c")</td>
                                <td>@((line.Quantity * line.Product.Price).ToString("c"))</td>
                                <td class="text-center">
                                    <form asp-page-handler="Remove" method="POST">
                                        <input type="hidden" name="ProductId" value="@line.Product.ProductId" />
                                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                                        <button class="btn-text btn-small" style="color: rgba(185, 0, 0, 100);" type="submit"><i class="fa fa-times-circle fa-2x"></i></button>
                                    </form>
                                </td>
                            </tr>
                        }       
                    </tbody>
                </table>
            </div> 
            <div class="checkout-coupon-form ws-m">
                <a class="btn btn-ghost btn-round pull-right" href="@Model.ReturnUrl">Continue Shopping</a>
            </div> 
        </div>
        <div class="col-lg-3 totals-group">
            <div class="totals-heading">
                <h6>Card Totals</h6>
            </div>
            <div class="totals-content">
                <div class="total-group">
                    <h5>Total:</h5>
                    <p>@Model.Cart.ComputeTotalValues().ToString("c")</p>
                </div>
                <div class="checkout-btn-wrapper">
                    <a class="btn checkout-btn btn-round" asp-action="Checkout" asp-controller="Order">Go to Checkout</a>x
                </div>
            </div>
        </div>  
    </div>
</div>

Pages/Completed.cshtml
@page
<header class="page-title pt-large pt-light pt-plax-lg-light" data-stellar-background-ratio="0.4">
    <div class="container">
        <div>
            <div class="col-md-6">
                <h1 style="color: black;">Thanks!</h1>
                <h3 class="sub-heading">THANKS FOR PLACING ORDER #@OrderId</h3>                
            </div>
        </div>
    </div>
</header>  
<div class="container section">
    <h5>We'll ship your goods as soon as possible.</h5>
    <a class="btn btn-round btn-ghost" asp-controller="Home">Return to Store</a>
</div>

@functions{
    [BindProperty(SupportsGet = true)]
    public string OrderId { get; set; }
}

Pages/OrderFailed.cshtml
@page 
@model OrderFailedModel
<div class="text-center">
    <h4>Unable to place the order</h4>
    The Following Products has stock lesser than that you requested
    <table class="table table-sm table-striped table-bordered">
        <tbody>
            @foreach (CartLine item in Model.cart.Lines)
            {
                @if(item.Quantity < item.Product.StockQuantity)
                {
                    <tr>
                        <td>You have requested @item.Quantity @item.Product.Name (s)</td>
                        <td class="text-warning">But only @item.Product.StockQuantity left in stock</td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <a class="btn btn-light btn-round btn-small" asp-action="RedirectToCart">Change Product(s) Quantities</a>
</div>

Pages/_CartLayout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Sports Store</title>
        <link rel="shortcut icon" href="/lib/assets/images/favicon.ico">
        <!-- Bootstrap -->
        <link rel="stylesheet" href="/lib/assets/styles/vendor/bootstrap.min.css">
        <!-- Fonts -->
        <link rel="stylesheet" href="/lib/assets/fonts/et-lineicons/css/style.css">
        <link rel="stylesheet" href="/lib/assets/fonts/linea-font/css/linea-font.css">
        <link rel="stylesheet" href="/lib/assets/fonts/fontawesome/css/font-awesome.min.css">
        <!-- Slider -->
        <link rel="stylesheet" href="/lib/assets/styles/vendor/slick.css">
        <!-- Lightbox -->
        <link rel="stylesheet" href="/lib/assets/styles/vendor/magnific-popup.css">
        <!-- Animate.css -->
        <link rel="stylesheet" href="/lib/assets/styles/vendor/animate.css">
        <!-- Definity CSS -->
        <link rel="stylesheet" href="/lib/assets/styles/main.css">
        <link rel="stylesheet" href="/lib/assets/styles/responsive.css">
        <script src="/lib/assets/js/vendor/modernizr-2.8.3.min.js"></script>
    </head>
    <body id="page-top" data-spy="scroll" data-target=".navbar">
        <nav class="navbar navbar-default navbar-fixed-top mega navbar-trans navbar-trans-dark trans-helper">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>  
                    <a class="navbar-brand" asp-action="Index" asp-controller="Home"><img class="navbar-logo-dark" alt="Sports Store" src="/lib/assets/images/logo.png" /></a>                                      
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/">Home<span class="sr-only"></span></a></li>
                        <li><a href="/about">About<span class="sr-only"></span></a></li>
                    </ul>
                </div>
            </div>
        </nav>              
        <div>
            @RenderBody()            
        </div>
        <div class="ws-l"></div>
        <footer class="footer-litle">
            <div class="gray-bg">
                <!-- Contact Info -->
                <address>
                    <ul>
                        <!-- Address -->
                        <li>
                            <span class="linea-basic-map adr-icon"></span>
                            <div class="adr-group">
                                <span class="adr-heading">Address</span>
                                <span class="adr-info">100 Street, Il, Us</span>
                            </div>
                        </li>
                        <!-- Email -->
                        <li>
                            <span class="linea-basic-paperplane adr-icon"></span>
                            <div class="adr-group">
                                <span class="adr-heading">Email</span>
                                <span class="adr-info">sayhello@email.com</span>
                            </div>
                        </li>
                        <!-- Phone -->
                        <li>
                            <span class="linea-basic-smartphone adr-icon"></span>
                            <div class="adr-group">
                                <span class="adr-heading">Phone</span>
                                <span class="adr-info">+ 123 4567 890</span>
                            </div>
                        </li>
                    </ul>
                </address>
            </div><!-- / .gray-bg -->
            <!-- Social Links -->
            <div class="dark-bg">
                <div class="container footer-social-links">
                    <div class="row">
                        <ul>
                            <li></li>
                            <li><a href="#">facebook</a></li>
                            <li><a href="#">Twitter</a></li>
                            <li><a href="#">Instagram</a></li>
                            <li><a href="#">Discord</a></li>
                        </ul>
                    </div>
                </div><!-- / .container -->
            </div><!-- / .dark-bg -->
            <!-- Copyright -->
            <div class="copyright">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <small>&copy; 2021 Definity. Made by Sathiyaraman and Suhail Sherief</small>
                        </div>
                        <div class="col-md-6">
                            <small><a href="#page-top" class="pull-right to-the-top">To the top<i
                                        class="fa fa-angle-up"></i></a></small>
                        </div>
                    </div><!-- / .row -->
                </div><!-- / .container -->
            </div><!-- / .copyright -->
        </footer><!-- / .footer-litle -->
        <script src="/lib/assets/js/vendor/jquery-2.1.4.min.js"></script>
        <script src="/lib/assets/js/vendor/google-fonts.js"></script>
        <script src="/lib/assets/js/vendor/jquery.easing.js"></script>
        <script src="/lib/assets/js/vendor/jquery.waypoints.min.js"></script>
        <script src="/lib/assets/js/vendor/bootstrap.min.js"></script>
        <script src="/lib/assets/js/vendor/bootstrap-hover-dropdown.min.js"></script>
        <script src="/lib/assets/js/vendor/smoothscroll.js"></script>
        <script src="/lib/assets/js/vendor/jquery.localScroll.min.js"></script>
        <script src="/lib/assets/js/vendor/jquery.scrollTo.min.js"></script>
        <script src="/lib/assets/js/vendor/jquery.stellar.min.js"></script>
        <script src="/lib/assets/js/vendor/jquery.parallax.js"></script>
        <script src="/lib/assets/js/vendor/slick.min.js"></script>
        <script src="/lib/assets/js/vendor/jquery.easypiechart.min.js"></script>
        <script src="/lib/assets/js/vendor/countup.min.js"></script>
        <script src="/lib/assets/js/vendor/isotope.min.js"></script>
        <script src="/lib/assets/js/vendor/jquery.magnific-popup.min.js"></script>
        <script src="/lib/assets/js/vendor/wow.min.js"></script>
        <script src="/lib/assets/js/vendor/jquery.mb.YTPlayer.min.js"></script>
        <script src="/lib/assets/js/vendor/jquery.ajaxchimp.js"></script>
        <script src="/lib/assets/js/main.js"></script>
    </body>
</html>